# #Workflow files are the recipe for task automation. This is where actions are placed if I want to use them for a task.

# name: Docker Actions
# on: [push]

# jobs:
#   action:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: hello-action
#         uses: ./.github/actions/hello-world
#         with:
#           firstGreeting: "Learning Lab User"
